spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}4f85896c765777e9d537c91008858b7cbbb25c6668fb3f2efa906078a4af9d64'

token:
  expiration_time: 86400000
  secret: user_token_test_123456789_test_0123456789_test_token

gateway:
  ip: 119.67.102.178

order_service:
  url: http://order-service/%s/orders
  exception:
    order_is_empty: User's orders is empty.
